// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyjfc82JeASSQ92a7VxB2ZrCOyd0uvTRw',
    appId: '1:882858620997:web:32d8789999853e1ab40b2c',
    messagingSenderId: '882858620997',
    projectId: 'linkup-29270',
    authDomain: 'linkup-29270.firebaseapp.com',
    storageBucket: 'linkup-29270.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJe2e17NLkprM-TEMCeuEaduenrifcb44',
    appId: '1:882858620997:android:1e5597ed1d15ad0cb40b2c',
    messagingSenderId: '882858620997',
    projectId: 'linkup-29270',
    storageBucket: 'linkup-29270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGmL0u-gQQvQZTlRTfW5Yg_OFWofHo6M',
    appId: '1:882858620997:ios:6ce25ad51b73f4a8b40b2c',
    messagingSenderId: '882858620997',
    projectId: 'linkup-29270',
    storageBucket: 'linkup-29270.appspot.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqGmL0u-gQQvQZTlRTfW5Yg_OFWofHo6M',
    appId: '1:882858620997:ios:99600aabfa47db75b40b2c',
    messagingSenderId: '882858620997',
    projectId: 'linkup-29270',
    storageBucket: 'linkup-29270.appspot.com',
    iosBundleId: 'com.example.linkup.RunnerTests',
  );
}
